import = ["/home/luis/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 13
offset.x = 1
offset.y = 1

[font.bold]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"
style = "Mono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[window.dimensions]
columns = 200
lines = 50
