import = ["/home/luis/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 12

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Medium"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[window.dimensions]
columns = 140
lines = 40
